---
 - hosts: webservers 
   gather_facts: yes 
   tasks: 
#   - name: extract the tomact tar.gz file
 #    unarchive:
  #     src: /krishna/apache-tomcat-8.5.57.tar.gz 
   #    dest: /home/tomcat 
    #   remote_src: yes 
   - name: started the TOMCAt server 
     shell: ./startup.sh
     args:
       chdir: /home/tomcat/apache-tomcat-8.5.57/bin
  

